import { z } from 'zod';
import { durableMemorySchema } from './schema';
import { runMemoryMutationTransaction, saveMemory, updateMemory } from './store';
import type { DurableMemory, MemoryKind } from './types';

export const MEMORY_ARCHIVE_FORMAT = 'elara-memory-bank' as const;
export const MEMORY_ARCHIVE_VERSION = 1 as const;
export const MEMORY_ARCHIVE_MAX_RECORDS = 5_000;
export const MEMORY_ARCHIVE_MAX_BYTES = 5_000_000;

export const memoryArchiveSchema = z.object({
  format: z.literal(MEMORY_ARCHIVE_FORMAT),
  version: z.literal(MEMORY_ARCHIVE_VERSION),
  exportedAt: z.number().finite(),
  memories: z.array(durableMemorySchema).max(MEMORY_ARCHIVE_MAX_RECORDS),
}).strict();

export type MemoryArchive = z.infer<typeof memoryArchiveSchema>;

export interface MemoryArchiveImportOptions {
  folderId?: string | null;
}

export interface MemoryArchiveImportResult {
  imported: number;
  coreDemoted: number;
  relationshipLinksRestored: number;
}

function archiveBytes(text: string): number {
  return new TextEncoder().encode(text).length;
}

function assertTargetFolder(folderId: string | null | undefined): string | null {
  const value = folderId?.trim() ?? '';
  if (value.length > 256) throw new Error('Memory archive target folder is invalid.');
  return value || null;
}

function importedKind(kind: MemoryKind): MemoryKind {
  return kind === 'CORE' ? 'CONTEXTUAL' : kind;
}

export function createMemoryArchive(memories: readonly DurableMemory[], exportedAt = Date.now()): MemoryArchive {
  const parsed = memoryArchiveSchema.safeParse({
    format: MEMORY_ARCHIVE_FORMAT,
    version: MEMORY_ARCHIVE_VERSION,
    exportedAt,
    memories: memories.map((memory) => durableMemorySchema.parse(memory)),
  });
  if (!parsed.success) throw new Error('Could not create a valid memory archive.');
  return parsed.data;
}

export function serializeMemoryArchive(memories: readonly DurableMemory[], exportedAt = Date.now()): string {
  const text = JSON.stringify(createMemoryArchive(memories, exportedAt), null, 2);
  if (archiveBytes(text) > MEMORY_ARCHIVE_MAX_BYTES) throw new Error('Memory archive exceeds the export size limit.');
  return text;
}

export function parseMemoryArchiveText(text: string): MemoryArchive {
  if (archiveBytes(text) > MEMORY_ARCHIVE_MAX_BYTES) throw new Error('Memory archive exceeds the import size limit.');
  let raw: unknown;
  try { raw = JSON.parse(text) as unknown; }
  catch { throw new Error('Memory archive is not valid JSON.'); }
  const parsed = memoryArchiveSchema.safeParse(raw);
  if (!parsed.success) throw new Error('Memory archive format or records are invalid.');
  return parsed.data;
}

function remapRelationships(ids: readonly string[], idMap: ReadonlyMap<string, string>, selfId: string): string[] {
  const mapped: string[] = [];
  for (const oldId of ids) {
    const newId = idMap.get(oldId);
    if (!newId || newId === selfId || mapped.includes(newId)) continue;
    mapped.push(newId);
  }
  return mapped;
}

/**
 * Import an already-parsed or external archive into the one canonical memory
 * table. Archive IDs, folder IDs, provenance and autonomy consent are never
 * trusted as authority. New IDs are generated by saveMemory, all records land
 * in the user-selected scope, and relationships are remapped only among records
 * in this same import transaction.
 */
export async function importMemoryArchive(value: unknown, options: MemoryArchiveImportOptions = {}): Promise<MemoryArchiveImportResult> {
  const archive = memoryArchiveSchema.safeParse(value);
  if (!archive.success) throw new Error('Memory archive format or records are invalid.');
  const folderId = assertTargetFolder(options.folderId);
  const now = Date.now();
  let coreDemoted = 0;
  let relationshipLinksRestored = 0;

  await runMemoryMutationTransaction(async () => {
    const idMap = new Map<string, string>();
    const staged: Array<{ original: DurableMemory; saved: DurableMemory }> = [];

    for (const original of archive.data.memories) {
      const kind = importedKind(original.kind);
      if (kind !== original.kind) coreDemoted += 1;
      const saved = await saveMemory({
        kind,
        title: original.title,
        body: original.body,
        observedAt: original.observedAt,
        confidence: original.confidence,
        importance: original.importance,
        lifecycle: original.lifecycle,
        source: {
          source: 'import',
          createdAt: now,
          note: `archive-v${MEMORY_ARCHIVE_VERSION}:${original.source.source}:${original.id}`,
        },
        tags: original.tags,
        folderId,
        expiresAt: original.expiresAt,
        pinned: original.pinned === true,
        autonomyContext: false,
      });
      idMap.set(original.id, saved.id);
      staged.push({ original, saved });
    }

    for (const { original, saved } of staged) {
      const relationships = {
        relatedMemoryIds: remapRelationships(original.relatedMemoryIds, idMap, saved.id),
        supportingMemoryIds: remapRelationships(original.supportingMemoryIds, idMap, saved.id),
        conflictingMemoryIds: remapRelationships(original.conflictingMemoryIds, idMap, saved.id),
        supersedes: remapRelationships(original.supersedes, idMap, saved.id),
        supersededBy: remapRelationships(original.supersededBy, idMap, saved.id),
      };
      relationshipLinksRestored += Object.values(relationships).reduce((sum, ids) => sum + ids.length, 0);
      await updateMemory(saved.id, relationships);
    }
  });

  return { imported: archive.data.memories.length, coreDemoted, relationshipLinksRestored };
}