import type { GoogleToolDescriptor } from './contracts';

export const googleToolRegistry: readonly GoogleToolDescriptor[] = [
  { name: 'calendar.listEvents', risk: 'read', capability: 'calendar.events.read', description: 'List calendar events with explicit filters and pagination.' },
  { name: 'calendar.getEvent', risk: 'read', capability: 'calendar.events.read', description: 'Retrieve one calendar event.' },
  { name: 'calendar.createEvent', risk: 'write', capability: 'calendar.events.write', description: 'Create one calendar event.' },
  { name: 'calendar.updateEvent', risk: 'write', capability: 'calendar.events.write', description: 'Replace one calendar event resource.' },
  { name: 'calendar.patchEvent', risk: 'write', capability: 'calendar.events.write', description: 'Partially update selected calendar event fields.' },
  { name: 'calendar.moveEvent', risk: 'write', capability: 'calendar.events.write', description: 'Move an event to another calendar.' },
  { name: 'calendar.deleteEvent', risk: 'destructive', capability: 'calendar.events.write', description: 'Delete one calendar event.' },
  { name: 'tasks.listTaskLists', risk: 'read', capability: 'tasks.read', description: 'List task lists with pagination.' },
  { name: 'tasks.listTasks', risk: 'read', capability: 'tasks.read', description: 'List tasks with filtering and pagination.' },
  { name: 'tasks.getTask', risk: 'read', capability: 'tasks.read', description: 'Retrieve one task.' },
  { name: 'tasks.createTask', risk: 'write', capability: 'tasks.write', description: 'Create a task with optional hierarchy and position.' },
  { name: 'tasks.updateTask', risk: 'write', capability: 'tasks.write', description: 'Replace a task resource.' },
  { name: 'tasks.moveTask', risk: 'write', capability: 'tasks.write', description: 'Change task parent and/or sibling position.' },
  { name: 'tasks.deleteTask', risk: 'destructive', capability: 'tasks.write', description: 'Delete one task.' },
  { name: 'tasks.clearCompleted', risk: 'destructive', capability: 'tasks.write', description: 'Clear completed tasks from a list.' },
  { name: 'docs.getDocument', risk: 'read', capability: 'docs.read', description: 'Retrieve one Google document.' },
  { name: 'docs.createDocument', risk: 'write', capability: 'docs.write', description: 'Create a Google document.' },
  { name: 'docs.batchUpdate', risk: 'write', capability: 'docs.write', description: 'Apply explicit Google Docs batch updates.' },
  { name: 'chat.listMessages', risk: 'read', capability: 'chat.read', description: 'List messages in a Google Chat space.' },
  { name: 'chat.getMessage', risk: 'read', capability: 'chat.read', description: 'Retrieve one Google Chat message.' },
  { name: 'chat.createMessage', risk: 'write', capability: 'chat.write', description: 'Create a Google Chat message.' },
  { name: 'chat.updateMessage', risk: 'write', capability: 'chat.write', description: 'Partially update selected Google Chat message fields.' },
  { name: 'chat.deleteMessage', risk: 'destructive', capability: 'chat.write', description: 'Delete one Google Chat message.' },
  { name: 'gmail.listMessages', risk: 'read', capability: 'gmail.read', description: 'Search/list Gmail messages with explicit query and pagination.' },
  { name: 'gmail.getMessage', risk: 'read', capability: 'gmail.read', description: 'Retrieve one Gmail message at an explicit representation level.' },
  { name: 'gmail.listThreads', risk: 'read', capability: 'gmail.read', description: 'Search/list Gmail threads.' },
  { name: 'gmail.getThread', risk: 'read', capability: 'gmail.read', description: 'Retrieve one Gmail thread.' },
  { name: 'gmail.listLabels', risk: 'read', capability: 'gmail.read', description: 'List Gmail labels.' },
  { name: 'gmail.getLabel', risk: 'read', capability: 'gmail.read', description: 'Retrieve one Gmail label.' },
  { name: 'gmail.modifyMessage', risk: 'write', capability: 'gmail.modify', description: 'Add/remove labels on one message.' },
  { name: 'gmail.modifyThread', risk: 'write', capability: 'gmail.modify', description: 'Add/remove labels on one thread.' },
  { name: 'gmail.trashMessage', risk: 'destructive', capability: 'gmail.modify', description: 'Move one message to trash.' },
  { name: 'gmail.untrashMessage', risk: 'write', capability: 'gmail.modify', description: 'Restore one message from trash.' },
  { name: 'gmail.trashThread', risk: 'destructive', capability: 'gmail.modify', description: 'Move one thread to trash.' },
  { name: 'gmail.untrashThread', risk: 'write', capability: 'gmail.modify', description: 'Restore one thread from trash.' },
  { name: 'gmail.createLabel', risk: 'write', capability: 'gmail.modify', description: 'Create a Gmail user label.' },
  { name: 'gmail.updateLabel', risk: 'write', capability: 'gmail.modify', description: 'Update a Gmail user label.' },
  { name: 'gmail.deleteLabel', risk: 'destructive', capability: 'gmail.modify', description: 'Delete a Gmail user label.' },
  { name: 'gmail.sendMessage', risk: 'send', capability: 'gmail.send', description: 'Send an RFC 822 message on the authorized Gmail account.' },
];
