import type { GoogleToolDescriptor } from './contracts';

export const googleToolRegistry: readonly GoogleToolDescriptor[] = [
  { name: 'calendar.listEvents', risk: 'read', capability: 'calendar.events.read', exposure: 'gemini', description: 'List calendar events with explicit filters and pagination.' },
  { name: 'calendar.createEvent', risk: 'write', capability: 'calendar.events.write', exposure: 'gemini', description: 'Create a Calendar event with a title, start time, and end time.' },
  { name: 'tasks.listTaskLists', risk: 'read', capability: 'tasks.read', exposure: 'gemini', description: 'List task lists with pagination.' },
  { name: 'tasks.listTasks', risk: 'read', capability: 'tasks.read', exposure: 'gemini', description: 'List tasks with filtering and pagination.' },
  { name: 'tasks.getTask', risk: 'read', capability: 'tasks.read', exposure: 'gemini', description: 'Retrieve one task.' },
  { name: 'tasks.createTask', risk: 'write', capability: 'tasks.write', exposure: 'gemini', description: 'Create a task with optional hierarchy and position.' },
  { name: 'tasks.updateTask', risk: 'write', capability: 'tasks.write', exposure: 'gemini', description: 'Replace a task resource.' },
  { name: 'tasks.moveTask', risk: 'write', capability: 'tasks.write', exposure: 'gemini', description: 'Change task parent and/or sibling position.' },
  { name: 'tasks.deleteTask', risk: 'destructive', capability: 'tasks.write', exposure: 'gemini', description: 'Delete one task.' },
  { name: 'tasks.clearCompleted', risk: 'destructive', capability: 'tasks.write', exposure: 'gemini', description: 'Clear completed tasks from a list.' },
  { name: 'docs.getDocument', risk: 'read', capability: 'docs.read', exposure: 'internal', description: 'Retrieve the raw Google document resource. Adapter primitive; not Gemini-visible.' },
  { name: 'docs.inspectDocument', risk: 'read', capability: 'docs.read', exposure: 'gemini', description: 'Inspect a Google Doc as headings, paragraphs, and tables with index anchors.' },
  { name: 'docs.createDocument', risk: 'write', capability: 'docs.write', exposure: 'gemini', description: 'Create a Google document.' },
  { name: 'docs.insertText', risk: 'write', capability: 'docs.write', exposure: 'gemini', description: 'Insert text at an explicit document index from a prior inspect.' },
  { name: 'docs.appendParagraph', risk: 'write', capability: 'docs.write', exposure: 'gemini', description: 'Append a paragraph at the end of a Google Doc.' },
  { name: 'docs.replaceText', risk: 'write', capability: 'docs.write', exposure: 'gemini', description: 'Replace all occurrences of a text string in a Google Doc.' },
  { name: 'docs.batchUpdate', risk: 'write', capability: 'docs.write', exposure: 'internal', description: 'Apply explicit Google Docs batch updates. Adapter primitive; not Gemini-visible.' },
  { name: 'chat.listMessages', risk: 'read', capability: 'chat.read', exposure: 'internal', description: 'List messages in a Google Chat space. Deferred from Workspace v1.' },
  { name: 'chat.getMessage', risk: 'read', capability: 'chat.read', exposure: 'internal', description: 'Retrieve one Google Chat message. Deferred from Workspace v1.' },
  { name: 'chat.createMessage', risk: 'write', capability: 'chat.write', exposure: 'internal', description: 'Create a Google Chat message. Deferred from Workspace v1.' },
  { name: 'chat.updateMessage', risk: 'write', capability: 'chat.write', exposure: 'internal', description: 'Partially update selected Google Chat message fields. Deferred from Workspace v1.' },
  { name: 'chat.deleteMessage', risk: 'destructive', capability: 'chat.write', exposure: 'internal', description: 'Delete one Google Chat message. Deferred from Workspace v1.' },
  { name: 'gmail.listMessages', risk: 'read', capability: 'gmail.read', exposure: 'gemini', description: 'Search/list Gmail messages with explicit query and pagination.' },
  { name: 'gmail.getMessage', risk: 'read', capability: 'gmail.read', exposure: 'gemini', description: 'Retrieve one Gmail message at an explicit representation level.' },
  { name: 'gmail.listThreads', risk: 'read', capability: 'gmail.read', exposure: 'gemini', description: 'Search/list Gmail threads.' },
  { name: 'gmail.getThread', risk: 'read', capability: 'gmail.read', exposure: 'gemini', description: 'Retrieve one Gmail thread.' },
  { name: 'gmail.listLabels', risk: 'read', capability: 'gmail.read', exposure: 'gemini', description: 'List Gmail labels.' },
  { name: 'gmail.getLabel', risk: 'read', capability: 'gmail.read', exposure: 'gemini', description: 'Retrieve one Gmail label.' },
  { name: 'gmail.modifyMessage', risk: 'write', capability: 'gmail.modify', exposure: 'gemini', description: 'Add/remove labels on one message.' },
  { name: 'gmail.modifyThread', risk: 'write', capability: 'gmail.modify', exposure: 'gemini', description: 'Add/remove labels on one thread.' },
  { name: 'gmail.trashMessage', risk: 'destructive', capability: 'gmail.modify', exposure: 'gemini', description: 'Move one message to trash.' },
  { name: 'gmail.untrashMessage', risk: 'write', capability: 'gmail.modify', exposure: 'gemini', description: 'Restore one message from trash.' },
  { name: 'gmail.trashThread', risk: 'destructive', capability: 'gmail.modify', exposure: 'gemini', description: 'Move one thread to trash.' },
  { name: 'gmail.untrashThread', risk: 'write', capability: 'gmail.modify', exposure: 'gemini', description: 'Restore one thread from trash.' },
  { name: 'gmail.createLabel', risk: 'write', capability: 'gmail.labels', exposure: 'gemini', description: 'Create a Gmail user label.' },
  { name: 'gmail.updateLabel', risk: 'write', capability: 'gmail.labels', exposure: 'gemini', description: 'Update a Gmail user label.' },
  { name: 'gmail.deleteLabel', risk: 'destructive', capability: 'gmail.labels', exposure: 'gemini', description: 'Delete a Gmail user label.' },
  { name: 'gmail.sendMessage', risk: 'send', capability: 'gmail.send', exposure: 'gemini', description: 'Send an email with explicit recipients, subject, and body.' },
  { name: 'drive.searchFiles', risk: 'read', capability: 'drive.files.app.read', exposure: 'gemini', description: 'Search files inside Elara’s app-file boundary.' },
  { name: 'drive.searchLibrary', risk: 'read', capability: 'drive.library.read', exposure: 'gemini', description: 'Search the user’s broader Google Drive library. Requires Drive library consent.' },
  { name: 'drive.getFile', risk: 'read', capability: 'drive.files.app.read', exposure: 'gemini', description: 'Retrieve metadata for one Drive file in the app-file or library-read boundary.' },
  { name: 'drive.downloadFile', risk: 'read', capability: 'drive.files.app.read', exposure: 'gemini', description: 'Download one Drive file in the app-file or library-read boundary.' },
  { name: 'drive.createFile', risk: 'write', capability: 'drive.files.app.write', exposure: 'gemini', description: 'Create a Drive file with explicit metadata in the app-file boundary.' },
  { name: 'drive.updateFile', risk: 'write', capability: 'drive.files.app.write', exposure: 'gemini', description: 'Update explicit Drive file metadata in the app-file boundary.' },
  { name: 'drive.moveFile', risk: 'write', capability: 'drive.files.app.write', exposure: 'gemini', description: 'Move a Drive file between explicit parents in the app-file boundary.' },
  { name: 'sheets.getSpreadsheet', risk: 'read', capability: 'sheets.read', exposure: 'gemini', description: 'Inspect spreadsheet metadata including sheet names, ids, and grid bounds.' },
  { name: 'sheets.readRange', risk: 'read', capability: 'sheets.read', exposure: 'gemini', description: 'Read an explicit A1 range from a spreadsheet.' },
  { name: 'sheets.writeRange', risk: 'write', capability: 'sheets.write', exposure: 'gemini', description: 'Write bounded rows to an explicit A1 range.' },
  { name: 'sheets.appendRows', risk: 'write', capability: 'sheets.write', exposure: 'gemini', description: 'Append bounded rows to an explicit spreadsheet range.' },
  { name: 'sheets.updateCell', risk: 'write', capability: 'sheets.write', exposure: 'gemini', description: 'Write a single value to an explicit A1 cell.' },
  { name: 'sheets.insertRows', risk: 'write', capability: 'sheets.write', exposure: 'gemini', description: 'Insert empty rows into a sheet at an explicit index.' },
  { name: 'sheets.batchUpdate', risk: 'write', capability: 'sheets.write', exposure: 'internal', description: 'Apply explicit spreadsheet batch update requests. Adapter primitive; not Gemini-visible.' },
  { name: 'roleplay_setting.list', risk: 'read', capability: 'roleplay.world.local', exposure: 'gemini', description: 'List persistent Roleplay World Canvas entities.' },
  { name: 'roleplay_setting.inspect', risk: 'read', capability: 'roleplay.world.local', exposure: 'gemini', description: 'Inspect one persistent Roleplay World Canvas entity by id or ref.' },
  { name: 'roleplay_setting.create', risk: 'write', capability: 'roleplay.world.local', exposure: 'gemini', description: 'Propose creation of a persistent Roleplay World Canvas entity.' },
  { name: 'roleplay_setting.update', risk: 'write', capability: 'roleplay.world.local', exposure: 'gemini', description: 'Propose changes to a persistent Roleplay World Canvas entity.' },
  { name: 'roleplay_setting.move', risk: 'write', capability: 'roleplay.world.local', exposure: 'gemini', description: 'Propose moving a persistent Roleplay World Canvas entity.' },
  { name: 'roleplay_setting.delete', risk: 'destructive', capability: 'roleplay.world.local', exposure: 'gemini', description: 'Propose deletion of a persistent Roleplay World Canvas entity and its descendants.' },
];
