import type { GoogleToolDescriptor } from './contracts';

export const googleToolRegistry: readonly GoogleToolDescriptor[] = [
  { name: 'calendar.listEvents', risk: 'read', capability: 'calendar.events.read', description: 'List calendar events with explicit filters and pagination.' },
  { name: 'tasks.listTaskLists', risk: 'read', capability: 'tasks.read', description: 'List task lists with pagination.' },
  { name: 'tasks.listTasks', risk: 'read', capability: 'tasks.read', description: 'List tasks with filtering and pagination.' },
  { name: 'tasks.getTask', risk: 'read', capability: 'tasks.read', description: 'Retrieve one task.' },
  { name: 'tasks.createTask', risk: 'write', capability: 'tasks.write', description: 'Create a task with optional hierarchy and position.' },
  { name: 'tasks.updateTask', risk: 'write', capability: 'tasks.write', description: 'Replace a task resource.' },
  { name: 'tasks.moveTask', risk: 'write', capability: 'tasks.write', description: 'Change task parent and/or sibling position.' },
  { name: 'tasks.deleteTask', risk: 'destructive', capability: 'tasks.write', description: 'Delete one task.' },
  { name: 'tasks.clearCompleted', risk: 'destructive', capability: 'tasks.write', description: 'Clear completed tasks from a list.' },
  { name: 'docs.getDocument', risk: 'read', capability: 'docs.read', description: 'Retrieve one Google document.' },
  { name: 'docs.createDocument', risk: 'write', capability: 'docs.write', description: 'Create a Google document.' },
  { name: 'docs.batchUpdate', risk: 'write', capability: 'docs.write', description: 'Apply explicit Google Docs batch updates.' },
  { name: 'chat.listMessages', risk: 'read', capability: 'chat.read', description: 'List messages in a Google Chat space.' },
  { name: 'chat.getMessage', risk: 'read', capability: 'chat.read', description: 'Retrieve one Google Chat message.' },
  { name: 'chat.createMessage', risk: 'write', capability: 'chat.write', description: 'Create a Google Chat message.' },
  { name: 'chat.updateMessage', risk: 'write', capability: 'chat.write', description: 'Partially update selected Google Chat message fields.' },
  { name: 'chat.deleteMessage', risk: 'destructive', capability: 'chat.write', description: 'Delete one Google Chat message.' },
  { name: 'gmail.listMessages', risk: 'read', capability: 'gmail.read', description: 'Search/list Gmail messages with explicit query and pagination.' },
  { name: 'gmail.getMessage', risk: 'read', capability: 'gmail.read', description: 'Retrieve one Gmail message at an explicit representation level.' },
  { name: 'gmail.listThreads', risk: 'read', capability: 'gmail.read', description: 'Search/list Gmail threads.' },
  { name: 'gmail.getThread', risk: 'read', capability: 'gmail.read', description: 'Retrieve one Gmail thread.' },
  { name: 'gmail.listLabels', risk: 'read', capability: 'gmail.read', description: 'List Gmail labels.' },
  { name: 'gmail.getLabel', risk: 'read', capability: 'gmail.read', description: 'Retrieve one Gmail label.' },
  { name: 'gmail.modifyMessage', risk: 'write', capability: 'gmail.modify', description: 'Add/remove labels on one message.' },
  { name: 'gmail.modifyThread', risk: 'write', capability: 'gmail.modify', description: 'Add/remove labels on one thread.' },
  { name: 'gmail.trashMessage', risk: 'destructive', capability: 'gmail.modify', description: 'Move one message to trash.' },
  { name: 'gmail.untrashMessage', risk: 'write', capability: 'gmail.modify', description: 'Restore one message from trash.' },
  { name: 'gmail.trashThread', risk: 'destructive', capability: 'gmail.modify', description: 'Move one thread to trash.' },
  { name: 'gmail.untrashThread', risk: 'write', capability: 'gmail.modify', description: 'Restore one thread from trash.' },
  { name: 'gmail.createLabel', risk: 'write', capability: 'gmail.labels', description: 'Create a Gmail user label.' },
  { name: 'gmail.updateLabel', risk: 'write', capability: 'gmail.labels', description: 'Update a Gmail user label.' },
  { name: 'gmail.deleteLabel', risk: 'destructive', capability: 'gmail.labels', description: 'Delete a Gmail user label.' },
  { name: 'gmail.sendMessage', risk: 'send', capability: 'gmail.send', description: 'Send an RFC 822 message on the authorized Gmail account.' },
  { name: 'drive.searchFiles', risk: 'read', capability: 'drive.files.read', description: 'Search or list authorized Drive files with explicit filters and pagination.' },
  { name: 'drive.getFile', risk: 'read', capability: 'drive.files.read', description: 'Retrieve metadata for one authorized Drive file.' },
  { name: 'drive.downloadFile', risk: 'read', capability: 'drive.files.read', description: 'Download one authorized Drive file.' },
  { name: 'drive.createFile', risk: 'write', capability: 'drive.files.write', description: 'Create a Drive file with explicit metadata.' },
  { name: 'drive.updateFile', risk: 'write', capability: 'drive.files.write', description: 'Update explicit Drive file metadata.' },
  { name: 'drive.moveFile', risk: 'write', capability: 'drive.files.write', description: 'Move a Drive file between explicit parents.' },
  { name: 'sheets.getSpreadsheet', risk: 'read', capability: 'sheets.read', description: 'Retrieve bounded spreadsheet metadata.' },
  { name: 'sheets.readRange', risk: 'read', capability: 'sheets.read', description: 'Read an explicit A1 range from a spreadsheet.' },
  { name: 'sheets.writeRange', risk: 'write', capability: 'sheets.write', description: 'Write bounded rows to an explicit A1 range.' },
  { name: 'sheets.appendRows', risk: 'write', capability: 'sheets.write', description: 'Append bounded rows to an explicit spreadsheet range.' },
  { name: 'sheets.batchUpdate', risk: 'write', capability: 'sheets.write', description: 'Apply explicit spreadsheet batch update requests.' },
];
